name: Deploy Docker image

on:
  push:
    tags:
      - "*"

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  LOCAL_ORG: lemmynsfw
  LOCAL_REPO: lemmy-ui

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.LOCAL_ORG }}
          password: ${{ env.PERSONAL_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.LOCAL_ORG }}/${{ env.LOCAL_REPO }}:${{ github.ref_name }}
